# Generated by Django 4.2.2 on 2023-06-20 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='patient_pics')),
                ('username', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('lane1', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('pincode', models.IntegerField()),
                ('type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='patient_pics')),
                ('username', models.CharField(max_length=122)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('lane1', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='patient_pics')),
                ('username', models.CharField(max_length=122)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('lane1', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
