# Generated by Django 4.2.2 on 2023-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthcare', '0002_details_doctordetails_patientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profile_pic',
            field=models.ImageField(upload_to='media/pictures/%Y'),
        ),
    ]
