# Generated by Django 4.2.2 on 2023-06-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthcare', '0003_alter_details_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorDetails',
        ),
        migrations.DeleteModel(
            name='PatientDetails',
        ),
    ]
