# Generated by Django 4.2.2 on 2023-06-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthcare', '0004_delete_doctordetails_delete_patientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profile_pic',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
