# Generated by Django 4.2.2 on 2023-06-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthcare', '0005_alter_details_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
