# Generated by Django 4.2.2 on 2023-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthcare', '0009_alter_details_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='media/blog_images')),
                ('category', models.CharField(max_length=122)),
                ('summary', models.CharField(max_length=122)),
                ('content', models.TextField()),
            ],
        ),
    ]
