# Generated by Django 4.2.2 on 2023-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthcare', '0011_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='id',
        ),
        migrations.AddField(
            model_name='blogs',
            name='uniqueid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
