# Generated by Django 4.2.2 on 2023-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthcare', '0013_alter_blogs_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='uniqueid',
            field=models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
